config/routes.rb
JapaneseGlossary::Application.routes.draw do
  resources :users, :only => ['new', 'create', 'show']
  get '/login', :to => 'user_sessions#new', :as => 'login'
  post '/login', :to => 'user_sessions#create'
  get '/logout', :to => 'user_sessions#destroy'
  get 'words/sound'
  root :to => 'glossaries#index'
  resources :words do
    member do
      get 'removesound'
    end
  end
  resources :mp3sounds, :only => ["show"]
  resources :glossaries do
    collection do
      get 'search'
      post 'search'
    end
  end

end

app/models/glossary.rb
class Glossary < ActiveRecord::Base
	has_many :words
end

app/models/mp3_sound.rb
class Mp3Sound < ActiveRecord::Base
	belongs_to :word
end

app/models/user.rb
class User < ActiveRecord::Base
	acts_as_authentic
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/models/word.rb
class Word < ActiveRecord::Base
	belongs_to :glossary
	has_one :mp3_sound

	def as_json (options)
		{ :id => id, 
			:english => english, 
			:romaji => romaji, 
			:japanese => japanese, 
			:glossary_id => glossary_id, 
			:glossary_name => glossary.glossary,
			:mp3sound_url => (mp3_sound_id.nil?) ? "" : Rails.application.routes.url_helpers.mp3sound_url(:host => "japaneseglossary.herokuapp.com", :id => mp3_sound_id) }
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  #filter_parameter_logging :password

	helper_method :current_user

	private

	def current_user_session
	  return @current_user_session if defined?(@current_user_session)
	  @current_user_session = UserSession.find
	end

	def current_user
	  return @current_user if defined?(@current_user)
	  @current_user = current_user_session && current_user_session.record
	end

end

app/controllers/glossaries_controller.rb
class GlossariesController < ApplicationController

	def index
		redirect_to login_url if current_user.nil?
		@glossaries = Glossary.all
	end

	def show
		@glossary = Glossary.find(params[:id])
		@words = @glossary.words
		respond_to do |format|
			format.js
		end
	end

	def search
		@query = params[:query] || ''
		response.headers['Content-type'] = 'application/json; charset=utf-8'
		@words = Word.includes(:glossary).where("english like '%#{@query}%' or romaji like '%#{@query}%' or japanese like '%#{@query}%'")
		respond_to do |format|
			format.html { render :layout => false }
			format.json { render :json => { :words => @words } }
		end
	end
end

app/controllers/mp3sounds_controller.rb
class Mp3soundsController < ApplicationController
	def show
		@mp3_sound = Mp3Sound.find(params[:id])
		send_data @mp3_sound.sound, :type => 'audio/mpeg'
	end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  
  def index
    user = UserSession.find
    render :text => 'Session User : ' + current_user.username + ' ' + current_user.id.to_s
  end
  
  # GET /user_sessions/new
  # GET /user_sessions/new.json
  def new
    redirect_to glossaries_url unless current_user.nil?
    @user_session = UserSession.new
  end

  
  # POST /user_sessions
  # POST /user_sessions.json
  def create
    @user_session = UserSession.new(params[:user_session])

    if @user_session.save
      respond_to do |format|
        format.html { redirect_to glossaries_url }
        format.json { render :json => { :result => 'success' } }
      end
    else
      respond_to do |format|
        format.html { render action: "new" }
        format.json { render :json => { :result => 'failed' } }
      end
    end
  end

  # DELETE /user_sessions/1
  # DELETE /user_sessions/1.json
  def destroy
    @user_session = UserSession.find
    @user_session.destroy

    redirect_to login_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
	def index
		respond_to do |format|
			format.js
		end
	end

	def edit
		@word = Word.find(params[:id])
	end

	def update
		@word = Word.find(params[:id])
		@file = params[:upload]
		unless @file.blank?
			@sound = Mp3Sound.new
			@sound.sound = @file.read
			@sound.save
			@word.mp3_sound_id = @sound.id
			@word.save
		end
		redirect_to edit_word_url(@word)
	end

	def sound
		@sound = Mp3Sound.find(6)
		send_data @sound.sound, :type => 'audio/mpeg'
	end

	def removesound
		@word = Word.find(params[:id])
		unless @word.mp3_sound_id.nil?
			@file = Mp3Sound.find(@word.mp3_sound_id)
			@file.destroy
			@word.mp3_sound_id = nil
			@word.save
		end
		redirect_to edit_word_url(@word)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/glossaries_helper.rb
module GlossariesHelper
end

app/helpers/mp3sounds_helper.rb
module Mp3soundsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/glossaries/index.html.haml
#small-main-header
	Japanese Glossary
.glossary-menu
	- @glossaries.each do |glossary|
		= link_to glossary.glossary, glossary_url(glossary), :remote => true
	= link_to 'Logout', logout_url, { :id => 'logout_link' }
#search-container
	Search &nbsp;&nbsp;
	= text_field_tag 'search', '', { :autocomplete => 'off' }
	= image_tag 'loading.gif', :id => 'loading_img'
#results

app/views/glossaries/search.html.haml
%table
	%tr
		%th English
		%th Romaji
		%th Japanese
	- @words.each do |word|
		%tr.word
			%td= word.english
			%td= word.romaji
			%td= word.japanese
	- if @words.size == 0
		%tr
			%td.word{:colspan => 3} No Results found.

app/views/glossaries/show.js.erb
$("#results").html("");
$("#search").val('');
var content = '';
<% @words.each do |word| %>
	content += "<tr class=\"word\"><td><%= word.english %></td><td><%= word.romaji %></td><td><%= word.japanese %></tr>";
<% end %>
$("#results").append("<table><tr><th>English</th><th>Romaji</th><th>Japanese</th></tr>" + content + "</table>")
$("#loading_img").hide();

app/views/layouts/application.html.haml
!!!
%html
	%head
		%title JapaneseGlossary
		= stylesheet_link_tag    "application", :media => "all"
		= javascript_include_tag "application"
		= csrf_meta_tags
%body
	= yield

app/views/user_sessions/_form.html.haml
= form_for @user_session, :url => login_path do |f|
  .label-element
    = f.label :username
    = f.text_field :username
    = f.label :password
    = f.password_field :password
    = f.submit 'Login', :class => 'default-button'

app/views/user_sessions/new.html.haml
%div
	#main-header
		%h3#main-header-text
			Japanese Glossary
	#signup-container
		.medium-title
		= render 'form'
	- if @user_session.errors.any?
		.error-messages
			- @user_session.errors.full_messages.each do |msg|
				.error-message= msg

app/views/words/edit.html.haml
%h2= @word.english
%h2= @word.romaji
%h2= @word.japanese
= form_for(@word, :url => word_url(@word), :html => { :multipart => true }) do |f|
	%h3 Sound File
	- if @word.mp3_sound_id.nil?
		= file_field_tag 'upload'
		= f.submit 'Submit'
	- else
		File Exists
		= link_to 'Delete', removesound_word_url(@word)

app/views/words/index.html.haml
.word
	Test

app/views/words/index.js.haml
$("#words").html("Testing");